### ISSUE TITLE
feat: 기본 페이지 생성

### ISSUE THREAD

**Issue by JinJeon** [JinJeon/musinsa#13]
## DESCRIPTION

- 네트워크가 느릴 시 JS 파일 컴파일 전 보여줄 스크립트 생성
- 사용하지 않는 파일 제거

## TODO

- [x] 네트워크가 느릴 시 JS파일 컴파일 전 보여줄 html 작성
- [x] html에 스타일 적용
- [x] 컴파일 완료 시 스크립트가 보이지 않도록 설정
- [x] 사용하지 않는 파일 제거
